Turob::Streams::TagBuilder can set targets attribute on stream tag
hotwired/turbo-rails pull request #194
Opened 2021-06-30 00:01 UTC by t27duck

https://github.com/hotwired/turbo/pull/113 allowed for multiple targets in turbo frame streams. This attempts to expose the feature to the Rails turbo_stream tag helper. Instead of a `target` which results in a call to `document.getElementById` on the JS level, a `targets` attribute will be passed into `document.querySelectorAll`

I'm not 100% happy with the "API" to invoke it, but it's the best I could come up with. Feedback appreciated.

The gist of it is the turbo stream tag builder helpers now accept a `target_multiple` keyword arg (default `false`). When set to `true` the end result of the tag will have a `targets` attribute instead of a `target` attribute.

I purposfully did not touch the ActionCable-related part of the gem as I think its usecase is mostly geared to always updating one element at a time. Regardless, if it were to get this feature, I think it would be better in a separate pull request. For now, I think giving the developer the abiltiy to target multiple elements at once in the turbo stream response from a controller is ok for now.

The test included is pretty much a copy/paste of an existing test, but invoking the new code path.

2021-06-30 23:54 UTC, dhh requested changes
Let's go with separate method calls rather than overloading existing ones.

2021-06-30 23:54 UTC, dhh commented on app/models/turbo/streams/tag_builder.rb
> +  def remove(target, target_multiple: false)
I'd rather see us add a separate `#remove_all(targets)` method than overloading this one.

2021-06-30 23:54 UTC, dhh commented on app/models/turbo/streams/tag_builder.rb
> +  def before(target, content = nil, target_multiple: false, **rendering, &block)
Same as with remove. Add a `before_all`.

2021-06-30 23:54 UTC, dhh commented on app/models/turbo/streams/tag_builder.rb
> +  def action(name, target_or_targets, content = nil, target_multiple: false, allow_inferred_rendering: true, **rendering, &block)
`action_all` also.

2021-07-01 00:51 UTC, t27duck commented
> Let's go with separate method calls rather than overloading existing ones.

I like that idea. I'll see about getting that implemented here in the near future...

2021-07-01 19:15 UTC, t27duck commented
Reimplemented the PR where all the action methods now have an `_all` version. I also updated the commit message and PR description to reflect what's actually happening now. I'm liking this change much more than my original idea.

2021-07-16 21:09 UTC, merged