Fix deprecation in routing
hotwired/turbo-rails pull request #657
Opened 2024-08-02 02:33 UTC by atomaka

Fixes new deprecation in Rails from https://github.com/rails/rails/pull/52422 that marks paths as hash keys in routes for removal.

2024-08-02 12:56 UTC, seanpdoyle approved these changes

2024-08-06 14:24 UTC, igordepolli commented
Can anyone please merge the PR? The Rails warning for that is really annoying.

2024-08-06 17:11 UTC, rafaelfranca commented
The deprecation is in a non-released version of Rails. There is no reason to rush maintainers because you are using a non-released version of the framework that can change at any time.

2024-08-06 23:52 UTC, brunoprietog requested changes
Hi @atomaka, thanks for your contribution! I left a very minor suggestion

2024-08-06 23:52 UTC, brunoprietog commented on config/routes.rb
> +  get "recede_historical_location", to: "turbo/native/navigation#recede",  as: :turbo_recede_historical_location
```suggestion
  get "recede_historical_location", to: "turbo/native/navigation#recede", as: :turbo_recede_historical_location
```

2024-08-06 23:52 UTC, brunoprietog commented on config/routes.rb
> +  get "resume_historical_location", to: "turbo/native/navigation#resume",  as: :turbo_resume_historical_location
```suggestion
  get "resume_historical_location", to: "turbo/native/navigation#resume", as: :turbo_resume_historical_location
```

2024-08-12 18:16 UTC, merged

2024-08-12 18:16 UTC, brunoprietog commented
Thanks @atomaka!